export const GET_ALL_FILM = 'GET_ALL_FILM';
export const SET_FILM_DANG_CHIEU = 'SET_FILM_DANG_CHIEU';
export const SET_FILM_SAP_CHIEU = 'SET_FILM_SAP_CHIEU';
export const AN_TRAILER = 'AN_TRAILER';
export const HIEN_TRAILER = 'HIEN_TRAILER';
